### ISSUE TITLE
[device-helper] Missing '@babel/runtime/regenerator'

### ISSUE THREAD

**Issue by cedricmessiant** [cozy/cozy-libs#246]
After I added `cozy-client` dependency to `cozy-konnector-google`, I've got this error on `cozy-client` import : 

```{ Error: Cannot find module '@babel/runtime/regenerator'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/cedric/dev/cozy-konnector-google/node_modules/cozy-device-helper/dist/apps.js:8:43)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/cedric/dev/cozy-konnector-google/node_modules/cozy-device-helper/dist/index.js:77:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/cedric/dev/cozy-konnector-google/node_modules/cozy-client/dist/authentication/mobile.js:22:25)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/cedric/dev/cozy-konnector-google/node_modules/cozy-client/dist/CozyClient.js:81:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/cedric/dev/cozy-konnector-google/node_modules/cozy-client/dist/index.js:7:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/cedric/dev/cozy-konnector-google/src/index.js:12:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at authenticate.then.then (/home/cedric/dev/cozy-konnector-google/node_modules/cozy-jobs-cli/src/konnector-dev.js:77:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3 code: 'MODULE_NOT_FOUND' } 'unexpected error'```

After `yarn add @babel/runtime`, everything works fine.
It seems that the line that causes the error in `cozy-device-helper/dist/apps.js` disapears after a rebuild

**Comment by ptbrowne** [comment]
`cozy-client` is on `cozy-device-helper@1.4.14` https://github.com/cozy/cozy-client/blob/master/packages/cozy-client/package.json#L14 . `cozy-device-helper` is at `1.6.3`, a version that does not contain any reference to `babel/runtime` in its dist files (presumably because we dropped support for old browsers). Can you upgrade cozy-device-helper in cozy-client and check if it resolves the problem ?

**Comment by cedricmessiant** [comment]
Thanks, `cozy-device-helper` upgrade in `cozy-client` solved the issue
