### ISSUE TITLE
[realtime] Sending messages before socket is fully opened

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-libs#466]
It seems the realtime Socket is sending message when the underlying websocket is not fully connected.

```
Uncaught (in promise) DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at Socket._callee$ (file:///android_asset/www/app.js:48207:33)
    at tryCatch (file:///android_asset/www/app.js:29981:40)
    at Generator.invoke [as _invoke] (file:///android_asset/www/app.js:30207:22)
    at Generator.prototype.(anonymous function) [as next] (file:///android_asset/www/app.js:30033:21)
    at asyncGeneratorStep (file:///android_asset/www/app.js:48022:103)
    at _next (file:///android_asset/www/app.js:48024:194)
    at <anonymous>
```

```
app.js:48207 Uncaught (in promise) DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at Socket._callee$ (file:///android_asset/www/app.js:48207:33)
    at tryCatch (file:///android_asset/www/app.js:29981:40)
    at Generator.invoke [as _invoke] (file:///android_asset/www/app.js:30207:22)
    at Generator.prototype.(anonymous function) [as next] (file:///android_asset/www/app.js:30033:21)
    at asyncGeneratorStep (file:///android_asset/www/app.js:48022:103)
    at _next (file:///android_asset/www/app.js:48024:194)
    at <anonymous>
```

**Comment by edas** [comment]
Les deux appels à `send` sont pourtant bien gardés derrière un `isOpen()`, autant sur la classe Realtime que sur la classe Socket.

Je vois un cas théorique dans https://github.com/cozy/cozy-libs/blob/master/packages/cozy-realtime/src/Socket.js#L123 

1- à partir d'une socket en erreur, L124 relance une nouvelle socket et attend qu'elle soit OPEN
2- la socket passe en OPEN mais l'event loop ne repasse pas encore la main à la L124
3- des trucs se passent, la socket tombe, quelque chose la relance et la socket en cours repasse en CONNECTING
4- l'event loop repasse la main à L124 vu que la promise avait réussi à l'étape 2
5- on continue donc l'exécution L134 alors que la socket en cours est toujours en CONNECTING

Ca me semble très tordu et peu probable que ce soit ça, mais on pourrait déjà se défendre du cas théorique en passant le `if` L123 en `while` (avec une clause pour jeter une erreur en cas de boucle infinie)

**Comment by edas** [comment]
Sinon (mais à priori non lié) : 

- Si jamais la socket est recréée en L123, je n'ai pas l'impression que la classe Realtime saura relancer les souscriptions qu'elle avait en cours. Me trompe-je ?
- Si jamais une socket est "CONNECTING" en L123 on va la remplacer et en recréer une nouvelle plutôt que d'attendre celle qui est en cours de connexion. Ca me parait dommage. Me trompe-je ?

**Comment by edas** [comment]
Closing, as it is related to an old version of realtime, before the rewrite of #967
